### ISSUE TITLE
BUG in ExpressionParser when evaluating $or

### ISSUE THREAD

**Issue by stfciz** [foursquare/fongo#15]
The ExpressionParser falls down when the query contains $or because the compare evaluation is absolutely wrong ...
- class :com.foursquare.fongo.impl.ExpressionParser
- method : private Filter buildExpressionFilter(final List<String> path, final Object expression) 
- BUG : if (path.get(0) == OR)  => see Java for dummies
- FIX : if (OR.equals(path.get(0)))

**Comment by hoffrocket** [comment]
thanks for reporiting!  i've fixed in master and will push out a new version soon.
