### ISSUE TITLE
FongoDBCollection.drop() causes ConcurrentModificationExcpetion

### ISSUE THREAD

**Issue by mchmielarz** [foursquare/fongo#25]
Hi!

Here is background of my case: I'm using NoSqlUnit to write some unit tests with database and FongoDB is used as in-memory version of MongoDB.

I receive ConcurrentModificationException during removing of all collections from FongoDB. Steps of removal are pretty straightforward (db is instance of FongoDB class):
- take all collection names using db.getCollectionNames() method,
- in for each name loop:
  - get collection by name using db.getCollection(collectionName)
  - and call collection.drop() where collection is an instance of FongoDBCollection class

This causes that ConcurrentModificationException arises on attempt to remove an entry from FongoDB's private collMap.

There are two possible solutions for this case:
1. Since FongoDB.getCollectionNames() returns only an immutable VIEW on key set of collMap private field every client using FongoDB should copy names collection to a new set.
2. FongoDB.getCollectionNames() should provide on every call a new set filled with keys of collMap field.

I think the latter option is the most interesting for users of the library. Am I right?

This is extremely important issue for my project and its unit tests. Is it possible (since it seems to be a small change) to provide the fix ASAP, please?

**Comment by hoffrocket** [comment]
Hi,

What version of fongo are using?  This might be fixed in 1.0.6, so please try that and let me know if you still see the problem.

https://github.com/foursquare/fongo/commit/0d6d2d2da6d6ab01cf4a5334c6cb66855827f696

**Comment by hoffrocket** [comment]
Ah, sorry.  I see this is a different issue.  I just fixed and pushed a snapshot to the maven repo.  change your version to 1.0.7-SNAPSHOT to get the change.  I'll push out a 1.0.7 release soon.

**Comment by mchmielarz** [comment]
Hi Jon,

I forgot to mention the version used. It's about 1.0.3.

BUT I've updated to 1.0.6 and it works!!! Thank you for the hint! :)

**Comment by mchmielarz** [comment]
@hoffrocket Is the 1.0.7 version finished? There is a change of version to 1.0.8-SNAPSHOT but I cannot find in maven repo v1.0.7. At oss.sonatype.org v1.0.7-SNAPSHOT is the latest one.

**Comment by hoffrocket** [comment]
i've just promoted 1.0.7 in the sonatype repo.  it should be available very soon

**Comment by mchmielarz** [comment]
it's there! :) thank you, Jon
