### ISSUE TITLE
ObjectId._new is not set to false when loading an object

### ISSUE THREAD

**Issue by chk-comsysto** [foursquare/fongo#28]
When I store an object in MongoDB, the newly generated ObjectId has _new set to true, but the ObjectId Serialization String is computed from _time, _machine, _inc (see ObjectId.toByteArray). When being deserialized (i.e. when the Object is loaded), _new is set to false (see ObjectId(String s)).

In fongo, however, there is no (de)serialization and the _new is never set to false in a simple save&retrieve object scenario. This causes problems when I try to update an object - the mongo driver is trying to handle it as an insert if _new==true. Currently updates only work as expected if I manually replace the ObjectId of a retrieved object before saving it:

xyz.setId(new ObjectId(xyz.getId().toString()))

I think it would make sense to ensure that ObjectId.notNew() is called whenever an object is stored in a FongoDBCollection.

**Comment by hoffrocket** [comment]
just pushed a 1.0.8 release with the fix

**Comment by chk-comsysto** [comment]
got a perfect replication of my test results with mongo now - thank you very much for the quick fix!
