### ISSUE TITLE
Problem with references

### ISSUE THREAD

**Issue by AlexM86** [foursquare/fongo#29]
Steps to reproduce:
I Have two classes "Test" and "TestSuite". Class "Test" have filed: private TestSuite testSuite; 
I'm trying to find "Test" object by "TestSuite" id using reference: testSuite.$id

log message:
find({ "testSuite.$id" : { "$oid" : "519f379fe44a690dc3258561"}}).limit(0).skip(0)

This doesn't work on fongo but work in real mongodb.

Thanks in advance
Alex

**Comment by hoffrocket** [comment]
Could you send the code to reproduce? I'm not sure what you mean exactly.

**Comment by AlexM86** [comment]
Please see source code:

import java.io.Serializable;
import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.hateoas.Identifiable;

@Document
public class TestSuite implements Serializable, Identifiable<String> {

```
@Id
private String idTestSuite;

@Override
public String getId() {
    return idTestSuite;
}

public String getIdTestSuite() {
    return idTestSuite;
}

public void setIdTestSuite(String idTestSuite) {
    this.idTestSuite = idTestSuite;
}   
```

}

mport java.io.Serializable;
import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.hateoas.Identifiable;

@Document
public class Test implements Serializable, Identifiable<String> {

```
public static final String TEST_SUITE = "test_suite";

@Id
private String idTest;

@FilterCriteria(TEST_SUITE)
@DBRef
private TestSuite testSuite;

@Override
public String getId() {
    return this.idTest;
}

public String getIdTest() {
    return idTest;
}

public void setIdTest(String idTest) {
    this.idTest = idTest;
}

public void setTestSuite(TestSuite testSuite) {
    this.testSuite = testSuite;
}

public TestSuite getTestSuite() {
    return testSuite;
}
```

}

**Comment by hoffrocket** [comment]
what is FilterCriteria?

**Comment by hoffrocket** [comment]
please also include some example code to reproduce the actual problem

**Comment by hoffrocket** [comment]
It would be most helpful if you forked the project and created a failing unit test that replicates this problem.  You can modify this class: https://github.com/foursquare/fongo/blob/master/src/test/java/com/foursquare/fongo/integration/SpringFongoTest.java
