### ISSUE TITLE
Unable to load only specific field for object(not all fields)

### ISSUE THREAD

**Issue by AlexM86** [foursquare/fongo#31]
I'm using spring MongoTemplate for accessing to the fongo.
I'm using criteria query for loading objects. I'm specifying only one field for loading. When I'm using real mongo database everything works as expected, but when I'm using fongo - all fields of object is loading

Query q = Query.query(Criteria.where("name").is("Demo1"));
        q.fields().include("data");
        List<MyObj> launches = operations.find(q, MyObj.class); 

Thanks in advance

**Comment by hoffrocket** [comment]
Hi, If you could for the project and add a test case to https://github.com/foursquare/fongo/blob/master/src/test/java/com/foursquare/fongo/integration/SpringFongoTest.java which duplicates the failure that would be very helpful.  Thanks
