### ISSUE TITLE
fongo should throw an exception when inserting duplicate keys

### ISSUE THREAD

**Issue by shollander** [foursquare/fongo#34]
When performing an "insert", mongo does not allow duplicate keys.  If an object with the same key already exists in the database, mongo will throw an exception (com.mongodb.MongoException.DuplicateKey).  Fongo does not duplicate this behavior.

**Comment by hoffrocket** [comment]
Fongo should throw a DuplicateKey Exception if you insert with a WriteConcern.SAFE or stricter (https://github.com/foursquare/fongo/blob/master/src/test/java/com/foursquare/fongo/FongoTest.java#L602) .  

Can you provide a code example (even better if you can fork the project and add a failing unit test) that demonstrates the problem?

**Comment by shollander** [comment]
I am using the spring-data MongoDB library like this, and no exception is thrown:

Sample Object:

``` java
public class Person {

    //field named id used by spring data for _id in mongo 
    private String id;
    private String name;

// getters, setters...
}
```

Failing Unit Test:

``` java
public class UnitTest {

    @Rule
    ExpectedException expectedException = ExpectedException.none();

    @Test
    public void test() {
        Fongo fongo = new Fongo("Test fongo");
        Mongo mongo = fongo.getMongo();
        mongo.setWriteConcern(WriteConcern.ACKNOWLEDGED);
        mongoOps = new MongoTemplate(new SimpleMongoDbFactory(mongo, "Unit test"));

        Person person = new Person();
        person.setId("12345");
        person.setName("John Doe");

        mongoOps.insert(person, "test collection");
        expectedException.expect(DuplicateKeyException.class);
        mongoOps.insert(person, "test collection");
    }
}        
```

When run against a real Mongo database, this unit test passes.

**Comment by hoffrocket** [comment]
fongo 1.1.0 has been released with the fix

**Comment by shollander** [comment]
That was quick!  Thanks!
