### ISSUE TITLE
regex operator matches nothing when pattern matching on multiple lines

### ISSUE THREAD

**Issue by izmailoff** [foursquare/fongo#36]
Tried both with Fongo 1.0.9 and 1.1.0.

I'm trying to use $regex (http://docs.mongodb.org/manual/reference/operator/regex/) in a way like this (MongoDB shell):

// multiline text that I will match:

> db.testdata.insert({ text: "one\ntwo\nthree"})

// single line text for comparison:

> db.testdata.insert({ text: "one 2two 3three"})

// no 's' option so dot does not match new line characters:

> db.testdata.find({ text: {$regex: 'one._two._'}})
> { "_id" : ObjectId("51b53a609b7dcea0d4150460"), "text" : "one 2two 3three" }
> 
> // this and the rest use 's' and other options and match properly:
> db.testdata.find({ text: {$regex: 'one._two._', $options: 's'}})
> { "_id" : ObjectId("51b53a209b7dcea0d415045f"), "text" : "one\ntwo\nthree" }
> { "_id" : ObjectId("51b53a609b7dcea0d4150460"), "text" : "one 2two 3three" }
> 
> db.testdata.find({ text: {$regex: 'one._two._', $options: 'sm'}})
> { "_id" : ObjectId("51b53a209b7dcea0d415045f"), "text" : "one\ntwo\nthree" }
> { "_id" : ObjectId("51b53a609b7dcea0d4150460"), "text" : "one 2two 3three" }
> 
> db.testdata.find({ text: {$regex: 'one._two._', $options: 'disum'}})
> { "_id" : ObjectId("51b53a209b7dcea0d415045f"), "text" : "one\ntwo\nthree" }
> { "_id" : ObjectId("51b53a609b7dcea0d4150460"), "text" : "one 2two 3three" }

The problem with Fongo is that document matches only when regex is on a single line, i.e. from the examples 'two' will match, but 'one._two._' will match nothing.

Just FYI I'm using:
CASE_INSENSITIVE | DOTALL | UNIX_LINES | UNICODE_CHARACTER_CLASS | UNICODE_CASE | MULTILINE
from java.util.regex.Pattern when compiling pattern. I use it after with 'matches' in Rogue DSL which works fine on real MongoDB.

Thanks!

**Comment by hoffrocket** [comment]
Can you provide a single example with its expected vs actual results?

**Comment by izmailoff** [comment]
Sure, I'll submit a pull request by the end of the day for a test in ExpressionParserTest and maybe a fix.
