### ISSUE TITLE
$min and $max

### ISSUE THREAD

**Issue by diegovar** [foursquare/fongo#39]
Does Fongo have support for $min and $max?

**Comment by hoffrocket** [comment]
No, it doesn't support those. Do you need them? it might be a bit tricky to implement to implement.

**Comment by diegovar** [comment]
It would be nice as we use them both, and it defeats the purpose of being able to drop Fongo as a Mongo replacement for our tests. At least the basic case of exact matching of a minimum and maximum object in the cursor response.

**Comment by twillouer** [comment]
Hi,

do you have a case test ?
I have done a (very) naive & simple version, I need to feed her :)

**Comment by diegovar** [comment]
I don't have a way of easily testing $min and $max to be honest, I can't
spare any cycles right now :(

**Comment by twillouer** [comment]
For now, I can hold things like : 

``` javascript
$match : {myId:{$in:[1,2,3]}},
$group : {_id:0, date:{"$max":"$date"}
```

with $skip, $limit, $sort handled.

You can try https://github.com/twillouer/fongo/tree/minmax and say me what to test :)

**Comment by twillouer** [comment]
@hoffrocket if you have time, can you take a look at https://github.com/twillouer/fongo/tree/minmax and say me how I can improve my code to help you ?
Thx

**Comment by hoffrocket** [comment]
thanks to @twillouer, 1.3.0 has been released with this feature
