### ISSUE TITLE
fongo does not ensure an unique index

### ISSUE THREAD

**Issue by chk-comsysto** [foursquare/fongo#40]
I've got the following Spring Data Annotation in my bean:

``` java
@Indexed(unique = true)
private String email;
```

which leads to the following index being created when fongo starts:

```
{ "v" : 1 , "key" : { "email" : 1} , "ns" : "test.user" , "name" : "email" , "dropDups" : false , "sparse" : false , "unique" : true}
```

However, the unique index is not ensured and this test fails, while it succeeds in mongo:

``` java
User user1 = createSampleUserWithEmail("sample@gmail.com");
User user2 = createSampleUserWithEmail("sample@gmail.com");
userRepository.save(user1);
assertEquals(1, userRepository.countAll());
userRepository.save(user2);
assertEquals(1, userRepository.countAll());
```

Note that a duplicate ID is not inserted, but this is another use case that is - for all I have experienced - not yet supported by fongo.

**Comment by hoffrocket** [comment]
fongo doesn't actually implement any indexes besides the _id index. it would be a pretty big change to support correctly. if you want to help create a patch i can provide guidance, but don't have time to implement this myself at the moment

**Comment by benjaminkomen** [comment]
I'm not sure how to interpret the commits referencing this issue, but has this been fixed yet?

**Comment by hoffrocket** [comment]
hello, the repo has moved here: https://github.com/fakemongo/fongo
please post issues there.
