### ISSUE TITLE
Fongo should return new objects or immutable (unmodifiable) objects/collections when find methods called

### ISSUE THREAD

**Issue by tom-ohare** [foursquare/fongo#43]
If I modify an object (or an object in a collection) returned by Fongo and then retrieve the same object from Fongo I see the 'new', changed object, not the one that was stored originally.

Here's some example code:

```
    Fongo fongo = new Fongo("mongo server 1");

    DB db = fongo.getDB("mydb");
    DBCollection coll = db.getCollection("mycollection");

    // Insert 2 objects
    DBObject bdo1 = new BasicDBObject("_id", 1).append("name", "tom");
    DBObject bdo2 = new BasicDBObject("_id", 2).append("name", "jon");

    coll.insert(bdo1);
    coll.insert(bdo2);

    // Get the 2nd one (name = jon) back
    DBObject bdo3 = coll.findOne(new BasicDBObject("_id",2));

    // Modify it locally
    bdo3.put("name", "jon2");

    // Retrieve the jon object again
    DBObject bdo4 = coll.findOne(new BasicDBObject("_id",2));

    LOG.info("bdo3 = {}", bdo3);  // Shows name='jon2'
    LOG.info("bdo4 = {}", bdo4);  // Also shows name='jon2'
```

I checked against MongoDB and it behaves as expected, ie with the code above, the name field of bdo3 is logged as 'jon2' but the name field of bdo4 is still 'jon'.

I guess this can be fixed by making the objects and collections returned by the various find methods immutable or by returning results in completely new objects (not referencing to the 'base' Fongo objects). 

That's probably a pain for 99% of tests but the above behaviour can be very time consuming to debug in an elaborate test case.

I'm using Fongo 1.1.0 and the 2.11.1 mongo-java-driver.

**Comment by tom-ohare** [comment]
Sorry, I closed the issue by mistake while fixing the format

**Comment by hoffrocket** [comment]
thanks. 1.1.1 released with this fix

**Comment by tom-ohare** [comment]
That was quick!
I just tried it and it works fine.
Thanks, Jon.
