### ISSUE TITLE
GeoNear

### ISSUE THREAD

**Issue by Millad** [foursquare/fongo#56]
I have written tests that uses MongoDB´s GeoNear feature. When using MongoDB via Spring Data the tests run green but when testing using Fongo the tests fail beacuse Fongo does not return the expected result like MongoDB when using GeoNear. 

Are there any issues with Fongo´s GeoNear?

**Comment by hoffrocket** [comment]
Fongo does not support the geo functions

**Comment by twillouer** [comment]
Any plan to do that ?

I will probably try this week-end if I had time.

**Comment by hoffrocket** [comment]
I wasn't planning on implementing. I think it would be a big effort.

**Comment by twillouer** [comment]
@Millad can you give me your geoNear command to see if I can adapt ?

**Comment by hoffrocket** [comment]
thanks to @twillouer, 1.3.0 has been released with this feature
