### ISSUE TITLE
MongoClient doesn't return correct MongoOptions and MongoClientOptions

### ISSUE THREAD

**Issue by twillouer** [foursquare/fongo#59]
Hi,

MockMongoClient retun null for both methods.

Why using `Objenesis`, I don't understand ?

I try with a very simple : 

``` java
 public static MockMongoClient create(Fongo fongo) {
    try {
      MockMongoClient client = new MockMongoClient();
      client.setFongo(fongo);
      return client;
    } catch (UnknownHostException uhe) {
      throw new RuntimeException(uhe);
    }
  }
```

and all tests are green ?

**Comment by hoffrocket** [comment]
I'm using Objenesis to prevent some initialization that occurs within the MongoClient that would leave threads running. I can add the MongoClientOptions.
