### ISSUE TITLE
$gte throws Exception on non-Comparable

### ISSUE THREAD

**Issue by yurgis** [foursquare/fongo#78]
When Fongo applies $gte to a field value which doesn't implement Comparable, it throws exception: com.foursquare.fongo.FongoException: stored value expected to be of type java.lang.Comparable but is { "origin" : "ABC" , "key" : "KEY-2"}.

The same situation doesn't produce an error in Mongo. Mongo calculates the comparison result to false.

Example:

> db.x.insert({a:{b:1, c:1}})
> db.x.insert({a:2})
> db.x.find()
> { "_id" : ObjectId("520cd390e829454261c64219"), "a" : { "b" : 1, "c" : 1 } }
> { "_id" : ObjectId("520cd39ce829454261c6421a"), "a" : 2 }
> db.x.find({a:{$gte:2}})
> { "_id" : ObjectId("520cd39ce829454261c6421a"), "a" : 2 }

**Comment by yurgis** [comment]
Moreover, there's one more strange thing I saw while investigation the issue.
If there are two conditions (AND-ed):
1st) some condition which is always false, $type:7 in my case
2nd) $gte described in the issue

then anyway there's exception about Comparable, through 1st condition should have already reduce the result to empty so there is no need to apply $gte.

**Comment by twillouer** [comment]
Hi,

you can try https://github.com/twillouer/fongo/tree/issue78 to test if it's correct the problem

**Comment by yurgis** [comment]
Hi,
it does solve the following: there's no exception now and non-Comparable docs are skipped as they should.
But it doesn't work fully correct.

DBQuery.greaterThanEquals("_id.left", new ObjectId("4ff300000000000000000100")) return 8 docs, which is not correct. These 8 docs are all docs in the collection which have ObjectId in _id.left field.
Also 2 of these 8 have object object id less than specified in query – 4ff300000000000000000001 and 4ff300000000000000000002.

And the query DBQuery.is("_id.left", new ObjectId("4ff300000000000000000101")).greaterThanEquals("_id.left", new ObjectId("4ff300000000000000000100")) returns the same 8 docs, which is not correct. Because 1st condition alone returns a single doc as it should.

Also the query DBQuery.lessThanEquals("_id.left", new ObjectId("4ff300000000000000000100")) returns empty result, which is not correct because there are two docs with _id.left less than specified.

**Comment by twillouer** [comment]
Sorry, but I don't understangd what is "_id.left".

I try this on my mongo : 

``` javascript
> db.test.find({"_id.left": {$gte:ObjectId("520e1a82507329549481bbdd")}});
```

this doesn't work, instead of : 

``` javascript
> db.test.find({"_id": {$gte:ObjectId("520e1a82507329549481bbdd")}});
{ "_id" : ObjectId("520e1a82507329549481bbdd"), "x" : 3 }
{ "_id" : ObjectId("520e1a82507329549481bbde"), "x" : 2.9 }
{ "_id" : ObjectId("520e1a82507329549481bbdf"), "x" : ISODate("2013-08-16T12:26:42.934Z") }
{ "_id" : ObjectId("520e1a82507329549481bbe0"), "x" : true }
{ "_id" : ObjectId("520e1a82507329549481bbe1"), "x" : { "$maxKey" : 1 } }
{ "_id" : ObjectId("520e1a83507329549481bbe2"), "x" : { "$minKey" : 1 } }
{ "_id" : ObjectId("520e2652507329549481bbe3"), "x" : false }
{ "_id" : ObjectId("520e2671507329549481bbe4"), "x" : 0 }
```

can you provide me test case ?

**Comment by yurgis** [comment]
Sorry for the confusing example. That's just a field in a composite id ( _id: {left: ..., right: ...} ).
I'll write a more clear example.

**Comment by yurgis** [comment]
Unfortunately the incorrect behavior doesn't fully reproduce with the simple test doc.
The following code show the 2nd part of the problem:

``` java
        dbColl.save(new BasicDBObject("x", new ObjectId("4ff300000000000000000101")));
        dbColl.save(new BasicDBObject("x", new ObjectId("4ff300000000000000000102")));
        dbColl.save(new BasicDBObject("x", new ObjectId("4ff300000000000000000103")));
        dbColl.save(new BasicDBObject("x", new ObjectId("4ff300000000000000000104")));

        System.out.println(dbColl.find().toArray());
        System.out.println(dbColl.find(DBQuery.greaterThanEquals("x", new ObjectId("4ff300000000000000000103"))).toArray());

        System.out.println(dbColl.find(DBQuery.is("x", new ObjectId("4ff300000000000000000103"))).toArray());
        System.out.println(dbColl.find(DBQuery.is("x", new ObjectId("4ff300000000000000000103")).greaterThanEquals("x", new ObjectId("4ff300000000000000000103"))).toArray());
```

The output:

```
[{ "_id" : { "$oid" : "521235bc75dc4f42cf04bd7d"} , "x" : { "$oid" : "4ff300000000000000000101"}}, { "_id" : { "$oid" : "521235bc75dc4f42cf04bd7e"} , "x" : { "$oid" : "4ff300000000000000000102"}}, { "_id" : { "$oid" : "521235bc75dc4f42cf04bd7f"} , "x" : { "$oid" : "4ff300000000000000000103"}}, { "_id" : { "$oid" : "521235bc75dc4f42cf04bd80"} , "x" : { "$oid" : "4ff300000000000000000104"}}]
[{ "_id" : { "$oid" : "521235bc75dc4f42cf04bd7f"} , "x" : { "$oid" : "4ff300000000000000000103"}}, { "_id" : { "$oid" : "521235bc75dc4f42cf04bd80"} , "x" : { "$oid" : "4ff300000000000000000104"}}]
[{ "_id" : { "$oid" : "521235bc75dc4f42cf04bd7f"} , "x" : { "$oid" : "4ff300000000000000000103"}}]
[{ "_id" : { "$oid" : "521235bc75dc4f42cf04bd7f"} , "x" : { "$oid" : "4ff300000000000000000103"}}, { "_id" : { "$oid" : "521235bc75dc4f42cf04bd80"} , "x" : { "$oid" : "4ff300000000000000000104"}}]
```

The last result is not correct. 104 should't be found beause of 1st condition.

This probably is another issue, not the one originally reported.

**Comment by yurgis** [comment]
I've investigated my "confusing example" deeper and found my mistake (misinterpreted id's I saw in toString, there were not only _id.left). Very sorry for that.
The following part of the reported above is not true:

> Also 2 of these 8 have object object id less than specified in query – 4ff300000000000000000001 and 4ff300000000000000000002.

So the only issue for now is about adding $gte to other conditions.

**Comment by yurgis** [comment]
I rewrote the code without MongoJack DBQuery and found that I'm wrong again. It's not a problem of Fongo.
DBQuery.someCondition("x", ...).anotherCondition("x", ...) replaces someCondition with anotherCondition when the field is the same.
So the solution for this issue works fine and complete.
