### ISSUE TITLE
Implement orderBy

### ISSUE THREAD

**Issue by rodriguezvalencia** [foursquare/fongo#88]
Hello guys,
We're using a bit of Fongo as well as real Mongo in our tests. We'd love to use Fongo more but it's unable to understand `orderBy`. Here's an example failing query (in rogue, scala syntax):

``` scala
(Banana where (_.size eqs "XXL") orderDesc(_.createdAt)).fetch
```

The same query without the `orderDesc` returns some values, once we add the ordering it returns `Nil`.

**Comment by hoffrocket** [comment]
Hi, I fixed a bug with findOne and orderby, but I don't think rogue uses that, so it might not address your issue.

please try 1.2.1-SNAPSHOT and let me know.

**Comment by ktoso** [comment]
Not sure where the SNAPSHOT is, but I'll compile from source and check :)

I also checked what JSON rogue generates and sends over the wire:

``` javascript
db.bananas.find({ "size" : "XXL"}).sort({ "createdAt" : -1})
```
