### ISSUE TITLE
Compatibility with Jongo

### ISSUE THREAD

**Issue by bgranvea** [foursquare/fongo#89]
I tested the latest Fongo version 1.2.0 and I noticed that there is an incompatibility with the Jongo library (http://jongo.org/) that I also use. I think it is due to the cloning of DB objects which doesn't work in this case.

Here is a unit test to reproduce the problem:

```
static class FongoJongoBean {
    private String str;
    private int num;
}

@Test
public void testFongoJongo() {
    Fongo fongo = new Fongo("Mocked Mongo server");
    Jongo jongo = new Jongo(fongo.getDB("test"));

    MongoCollection coll = jongo.getCollection("coll");

    coll.save(new FongoJongoBean());

    Iterator<FongoJongoBean> it = coll.find().as(FongoJongoBean.class).iterator();
    while (it.hasNext()) {
        System.out.println("obj=" + it.next());
    }
}
```

The code throws this exception:

java.lang.IllegalArgumentException: Don't know how to clone: { "num" : 0 , "_id" :  null }
    at com.foursquare.fongo.impl.Util.clone(Util.java:51)
    at com.mongodb.FongoDBCollection.copyResults(FongoDBCollection.java:413)
    at com.mongodb.FongoDBCollection.__find(FongoDBCollection.java:401)
    at com.mongodb.DBCursor._check(DBCursor.java:368)
    at com.mongodb.DBCursor._hasNext(DBCursor.java:459)
    at com.mongodb.DBCursor.hasNext(DBCursor.java:484)
    at org.jongo.MongoIterator.hasNext(MongoIterator.java:36)

The object given to Util has a type org.jongo.Insert$AlreadyCheckedDBObject which extends com.mongodb.LazyWriteableDBObject.

Could Util be enhanced to support this kind of objects?

Note: I'm also using a pre-release of Jongo 0.5. Here are my pom.xml:

```
    <dependency>
        <groupId>org.mongodb</groupId>
        <artifactId>mongo-java-driver</artifactId>
        <version>2.11.2</version>
    </dependency>

    <dependency>
        <groupId>com.foursquare</groupId>
        <artifactId>fongo</artifactId>
        <version>1.2.0</version>
    </dependency>

    <dependency>
        <groupId>org.jongo</groupId>
        <artifactId>jongo</artifactId>
        <version>0.5-early-20130912-1506</version>
    </dependency>
```

**Comment by twillouer** [comment]
Hi,

try using fongo 1.2.1-SNAPSHOT, it will work (i hope :))

**Comment by bgranvea** [comment]
yes, this issue seems fixed with 1.2.1-SNAPSHOT, thanks for the quick answer! But now I've got another unit test which doesn't work. Here is a test to reproduce the problem:

```
static class FongoJongoBean {
    private String key;
    private FongoJongoSubBean subBean;

    FongoJongoBean() {}

    FongoJongoBean(String key, FongoJongoSubBean subBean) {
        this.key = key;
        this.subBean = subBean;
    }
}

static class FongoJongoSubBean {
    private String value;

    FongoJongoSubBean() {}

    FongoJongoSubBean(String value) {
        this.value = value;
    }
}

@Test
public void testFongoJongo2() {
    Fongo fongo = new Fongo("Mocked Mongo server");
    Jongo jongo = new Jongo(fongo.getDB("test"));

    MongoCollection coll = jongo.getCollection("coll");

    coll.save(new FongoJongoBean("test", new FongoJongoSubBean("value")));

    int n = coll.update("{key: #}", "test")
        .with("{$set: {subBean: #}}", new FongoJongoSubBean("newValue"))
        .getN();
    assertTrue(n == 1);
}
```

The update operation fails with this exception:

java.lang.UnsupportedOperationException: Object is read only
    at org.bson.LazyBSONObject.put(LazyBSONObject.java:334)
    at com.mongodb.FongoDBCollection.filterLists(FongoDBCollection.java:135)
    at com.mongodb.FongoDBCollection.replaceListAndMap(FongoDBCollection.java:143)
    at com.mongodb.FongoDBCollection.filterLists(FongoDBCollection.java:134)
    at com.mongodb.FongoDBCollection.replaceListAndMap(FongoDBCollection.java:143)
    at com.mongodb.FongoDBCollection.filterLists(FongoDBCollection.java:134)
    at com.mongodb.FongoDBCollection.update(FongoDBCollection.java:178)
    at com.mongodb.DBCollection.update(DBCollection.java:178)
    at org.jongo.Update.with(Update.java:52)

I'm not sure of what filterLists is supposed to do but it seems that if it transforms the input parameters of update, it should work on clones, as it has been done for other operations.

**Comment by twillouer** [comment]
Hi, can you try https://github.com/twillouer/fongo/tree/issue-89 to see if all is ok ?

**Comment by bgranvea** [comment]
your patch seems ok, my unit tests are passing now, thanks!

**Comment by bgranvea** [comment]
Will your patch be included in next released version?

**Comment by twillouer** [comment]
don't know, I'm nothing here :)

**Comment by twillouer** [comment]
@hoffrocket hi, any idea when the next release will be realized?

**Comment by hoffrocket** [comment]
1.3.0 has been released with this fix
