### ISSUE TITLE
Implement elemMatch

### ISSUE THREAD

**Issue by nesderl** [foursquare/fongo#94]
Working in a project where we need to do some testing with Fongo on querying nested data structure using the `elemMatch` filter.

Would it be possible to have it implemented in one of the next releases ?

If not, I'm currently working on an implementation of it that I can submit as soon as it's working properly.

**Comment by twillouer** [comment]
Hi, can you try https://github.com/twillouer/fongo/tree/issue-94 ?

**Comment by hoffrocket** [comment]
1.3.0 has been released with this fix
