### ISSUE TITLE
java.lang.ClassNotFoundException: com.mongodb.Cursor

### ISSUE THREAD

**Issue by sameerarora** [foursquare/fongo#97]
I am getting a java.lang.ClassNotFoundException: com.mongodb.Cursor exception while trying to run a junit with fongo(1.5.5) and spring(3.2.4),  I looked at the fongo code in github and could not find any reference to com.mongodb.Cursor class.

I even checked out the latest code and added 1.5.7-SNAPSHOT dependency in my code but still getting the same error.

**Comment by twillouer** [comment]
Hi,

which version of mongodb driver do you use ?

**Comment by izmailoff** [comment]
Fongo 1.5.5 depends on mongo-java-driver 2.12.2 (http://mvnrepository.com/artifact/com.github.fakemongo/fongo/1.5.5). It's quite likely that you have an older driver. Maybe it's been pulled in automatically as a transitive dependency.

**Comment by twillouer** [comment]
yes, they depends of a new java driver, BUT this driver is provided

```
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>2.12.3</version>
            <scope>provided</scope>
        </dependency>
```

so, if you use an old implemtation of the java-driver, you will be in trouble. (fongo 1.5 is only compatible with 2.12, you must use fongo 1.4.X for older mongodb drivers)

**Comment by sameerarora** [comment]
Thanks , it worked for mongo java driver 2.12.2, 2.11.1 works with fongo 1.4.5

**Comment by sameerarora** [comment]
I was using 2.11.1 with 1.5.5 earlier when I got this error, it would be great if we could document the dependency map somewhere.

**Comment by thomas-bishop** [comment]
Wow. Thanks for this pointer! It was very strange since my test was running okay within the IDE, but i found it was failing when I ran it through Maven. Was quite a surprise. When I changed the dependency to the older one, it started working through Maven as well. Thanks!
-T
