### ISSUE TITLE
TTL is not supported?

### ISSUE THREAD

**Issue by jasonfungsing** [foursquare/fongo#98]
I have a ttl function in one of my collection. When I unit test it with fongo, seems the data is not delete from db.

Is this because of the fongo does not have a "mongod" running?

Btw, I made my unit test thread to sleep for more than 2 minutes which should have enough time for mongod to check ttl index and perform deletion.

**Comment by hoffrocket** [comment]
Hi,

The project has been moved: https://github.com/fakemongo/fongo
