### ISSUE TITLE
fongoDBCollection.rename("newname") results in CommandFailureException

### ISSUE THREAD

**Issue by g1l3sp** [foursquare/fongo#99]
Attempting to rename a collection using fongo throws an exception:

```
com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0 , "errmsg" : "no such cmd: renameCollection"}
    at com.mongodb.CommandResult.getException(CommandResult.java:76)
    at com.mongodb.CommandResult.throwOnError(CommandResult.java:140)
    at com.mongodb.DBCollection.rename(DBCollection.java:1314)
    ...
```

This method appears to be unimplemented (the generated command is unhandled anyway).  It'd be handy if it worked, and without knowing anything about the internals of fongo, it seems like it might be an easy one to add :-)

**Comment by hoffrocket** [comment]
hi @g1l3sp, sorry to ask you to do this, but could you please file this bug here: https://github.com/fakemongo/fongo

the project was moved. thanks.

**Comment by g1l3sp** [comment]
Sorry 'bout that, I had a tab open with the old repo, and mistakenly submitted this from there.  I just opened a new issue in the fakemongo repo.
